server:
  port: 8080
# DB config
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springplus?serverTimezone=Asia/Seoul
    username: root
    password: "!@Skdud340"
  # DB update
  jpa:
    hibernate:
      ddl-auto: update
    # sql
    properties:
      hibernate:
        show_sql: true
#        format_sql: true
jwt:
  secret:
    key: VWtkV2FtSXlVbXhKUjFwNVlqSXdaMUZ0Um5wYVZGa3dTVWRhZG1OdE1XaGtRVDA5